//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 复制磁力链接 的本地化字符串。
        /// </summary>
        public static string DetailCopyButton {
            get {
                return ResourceManager.GetString("DetailCopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即下载 的本地化字符串。
        /// </summary>
        public static string DetailDownloadButton {
            get {
                return ResourceManager.GetString("DetailDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件列表 的本地化字符串。
        /// </summary>
        public static string DetailFileList {
            get {
                return ResourceManager.GetString("DetailFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相关搜索关键字 的本地化字符串。
        /// </summary>
        public static string DetailRelatedSearchWords {
            get {
                return ResourceManager.GetString("DetailRelatedSearchWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你可能也喜欢 的本地化字符串。
        /// </summary>
        public static string DetailSoYouLike {
            get {
                return ResourceManager.GetString("DetailSoYouLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索BT资源，共索引了BT资源127,207,177个。 的本地化字符串。
        /// </summary>
        public static string IndexInputPlaceholder {
            get {
                return ResourceManager.GetString("IndexInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string IndexSubmitButton {
            get {
                return ResourceManager.GetString("IndexSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最好的BT资源搜索引擎，今日新增3,193个。 的本地化字符串。
        /// </summary>
        public static string IndexTips {
            get {
                return ResourceManager.GetString("IndexTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索资源 的本地化字符串。
        /// </summary>
        public static string InputPlaceholder {
            get {
                return ResourceManager.GetString("InputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string MagnetCreateTime {
            get {
                return ResourceManager.GetString("MagnetCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载次数 的本地化字符串。
        /// </summary>
        public static string MagnetDownloadCount {
            get {
                return ResourceManager.GetString("MagnetDownloadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件数 的本地化字符串。
        /// </summary>
        public static string MagnetFileCount {
            get {
                return ResourceManager.GetString("MagnetFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小 的本地化字符串。
        /// </summary>
        public static string MagnetFileSize {
            get {
                return ResourceManager.GetString("MagnetFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string MagnetType {
            get {
                return ResourceManager.GetString("MagnetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新时间 的本地化字符串。
        /// </summary>
        public static string MagnetUpdateTime {
            get {
                return ResourceManager.GetString("MagnetUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大家都在搜 的本地化字符串。
        /// </summary>
        public static string SearchKeyWords {
            get {
                return ResourceManager.GetString("SearchKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多 的本地化字符串。
        /// </summary>
        public static string SearchMoreButton {
            get {
                return ResourceManager.GetString("SearchMoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;strong&gt;如何才能找到下载速度快的资源？&lt;/strong&gt;&lt;div&gt;通常情况下，如果一个资源更新日期离现在比较近那一定有速度并且下载次数越多速度越快。&lt;/div&gt;&lt;div&gt;小伙伴们懂了吗？可以用排序功能，找&lt;b&gt;下载次数多的&lt;/b&gt;或者&lt;b&gt;比较新的&lt;/b&gt;资源，那下载速度一定是嗷嗷快。&lt;/div&gt; 的本地化字符串。
        /// </summary>
        public static string SearchTips {
            get {
                return ResourceManager.GetString("SearchTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据 &lt;b&gt;{0}&lt;/b&gt; 搜索到 &lt;b&gt;{1}&lt;/b&gt; 个相关资源 的本地化字符串。
        /// </summary>
        public static string SearchTotalCount {
            get {
                return ResourceManager.GetString("SearchTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BT香蕉（btbanana.com）是收录最快，最全的bt搜索引擎，共收录BT资源超过2亿个，每天新收录超过20万个。 的本地化字符串。
        /// </summary>
        public static string WebDescription {
            get {
                return ResourceManager.GetString("WebDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BT搜索，磁力搜索，电影资源搜索 的本地化字符串。
        /// </summary>
        public static string WebKeyWords {
            get {
                return ResourceManager.GetString("WebKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BT香蕉 的本地化字符串。
        /// </summary>
        public static string WebTitle {
            get {
                return ResourceManager.GetString("WebTitle", resourceCulture);
            }
        }
    }
}
